name: retail_products_app
description: A Flutter app for registering and listing products without barcodes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^0.8.7+3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
